#ifndef __DRIVER_H
#define __DRIVER_H

#define	FILE_DEVICE_IMMCPU	0x8000

#define IOCTL_IMMUNE_GETFLASH	\
	CTL_CODE(FILE_DEVICE_IMMCPU, 0x800,\
			 METHOD_OUT_DIRECT, FILE_READ_DATA)

#define	IOCTL_IMMUNE_GETMSR	\
	CTL_CODE(FILE_DEVICE_IMMCPU, 0x802,\
			 METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_IMMUNE_GETTXTPUB	\
	CTL_CODE(FILE_DEVICE_IMMCPU, 0x804,\
			 METHOD_OUT_DIRECT, FILE_READ_DATA)

#define MSR_IA32_FEATURE_CONTROL	0x3a
#define SENTER_GLOBAL_ENABLE_bm		(1ULL<<15)	// SENTER instructions
#define SENTER_LEAF_ENABLES_bm		0x7f00ULL	// SENTER instructions

#define CPUID_VENDOR	0x00
#define CPUID_MODEL		0x01

#define CPUID_EAX	0x00
#define CPUID_EBX	0x01
#define CPUID_ECX	0x02
#define CPUID_EDX	0x03

#define CPUID_MODEL_SMX_bm	(1UL<<6)

#endif	//__DRIVER_H
