apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Replace "api.example.com" with your webapp hostname.
# Replace "ingressclassname" with your Ingress class
patches:
  - patch: |-
      - op: add
        path: /spec/rules/0/host
        value: "api.example.com"
      - op: add
        path: /spec/ingressClassName
        value: "ingressclassname"
    target:
      kind: Ingress
      name: authsrv-v2
  - path: deployment-config.yaml
    target:
      kind: Deployment
      name: authsrv-deployment-v2
 
configMapGenerator:
  - name: authsrv-v2-config
    files:
      - settings.yml
      - credentials.yml.enc=empty-credentials.yml.enc

resources:
  - env-secret.yaml
