apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
stringData:
  admin-password: "<pg-admin-password>"
  apisrv-password: "<apisrv-role-password>"
  authsrv-password: "<authsrv-role-password>"
