{{- if .Values.ingress.enabled -}}
{{- $fullName := include "immune.fullname" . -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "immune.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 24m
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http{{ if .Values.ingress.tls }}s{{ end }}://*.{{ .Values.cors.hostname }}"
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.appsrv.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "immune.fullname" . }}-appsrv
                port:
                  number: 8000
              {{- else }}
              serviceName: {{ include "immune.fullname" . }}-appsrv
              servicePort: 8000
              {{- end }}
    - host: {{ .Values.apisrv.hostname | quote }}
      http:
        paths:
          {{- $ctx := . -}}
          {{- $paths := list "/v2/configuration" "/v2/info" "/v2/enroll" "/v2/attest" "/v2/policies" "/v2/devices" "/v2/appraisals" "/v2/changes" }}
          {{- range $paths }}
          - path: {{ . | quote }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "immune.fullname" $ctx }}-apisrv
                port:
                  number: 8000
              {{- else }}
              serviceName: {{ include "immune.fullname" $ctx }}-apisrv
              servicePort: 8000
              {{- end }}
          {{- end }}
    - host: {{ .Values.authsrv.hostname | quote }}
      http:
        paths:
          {{- $ctx := . -}}
          {{- $paths := list "/v2/organisations" "/v2/session" "/v2/users" "/v2/subscriptions" "/v2/memberships" "/v2/password_reset" "/v2/events" "/v2/healthy" "/v2/ready" "/v2/stripe_webhooks" "/v2/oauth" "/v2/appconfig" }}
          {{- range $paths }}
          - path: {{ . | quote }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "immune.fullname" $ctx }}-authsrv
                port:
                  number: 3000
              {{- else }}
              serviceName: {{ include "immune.fullname" $ctx }}-authsrv
              servicePort: 3000
              {{- end }}
          {{- end }}
{{- end }}