apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immune.fullname" . }}-apisrv-secrets
type: Opaque
stringData:
  bucket-secret: "{{ .Values.bucket.secret_key }}"
  lenovo-password: "{{ if .Values.inteltsc.enable }}{{ .Values.inteltsc.password }}{{- end }}"
  lenovo-secret: "{{ if .Values.inteltsc.enable }}{{ .Values.inteltsc.client_secret }}{{- end }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immune.fullname" . }}-db-secrets
type: Opaque
stringData:
  admin-password: "{{ .Values.postgres.admin.password }}"
  apisrv-password: "{{ .Values.postgres.apisrv.password }}"
  authsrv-password: "{{ .Values.postgres.authsrv.password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immune.fullname" . }}-authsrv-secrets
type: Opaque
stringData:
  RAILS_MASTER_KEY: "{{ .Values.authsrv.keys.rails_master_key }}"
  SECRET_KEY_BASE: "{{ .Values.authsrv.keys.secret_key_base }}"
  AUTHSRV_MAILGUN_API_KEY: "{{ if .Values.mailgun.enable }}{{ .Values.mailgun.api_key }}{{- end }}"
  AUTHSRV_STRIPE_SECRET_KEY: "{{ if .Values.stripe.enable }}{{ .Values.stripe.secret_key }}{{- end }}"
  AUTHSRV_STRIPE_WEBHOOK_SIGNING_SECRET: "{{ if .Values.stripe.enable }}{{ .Values.stripe.webhook_signing_key }}{{- end }}"
  AUTHSRV_GITHUB_API_SECRET: "{{ if .Values.github.enable }}{{ .Values.github.api_secret }}{{- end }}"
  AUTHSRV_GOOGLE_API_SECRET: "{{ if .Values.google.enable }}{{ .Values.google.api_secret }}{{- end }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immune.fullname" . }}-apisrv-keys
  labels:
    {{- include "immune.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  device-ca.key: "{{ .Values.apisrv.keys.enroll.priv }}"
  token.key: "{{ .Values.apisrv.keys.auth.priv }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immune.fullname" . }}-authsrv-keys
  labels:
    {{- include "immune.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  token.key: "{{ .Values.authsrv.keys.auth.priv }}"
