{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "immune.serviceAccountName" . }}
  labels:
    {{- include "immune.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "immune.serviceAccountName" . }}
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
      - watch
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "immune.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "immune.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "immune.serviceAccountName" . }}
  namespace: default
{{- end }}
