/* eslint-disable @next/next/no-img-element */
import Headline from 'components/elements/Headlines/Headline';
import Input from 'components/elements/Input/Input';
import Toggle from 'components/elements/Toggle/Toggle';

const UserEditTwoFactor: React.FC = () => {
  // TODO: Add functionality
  // TODO: Add Actionbar
  return (
    <div className="space-y-6">
      <Headline size={4}>2FA</Headline>
      <p>Protect your account by requiring an additional layer of security to sign in</p>
      <div className="">
        <div className="flex py-3 px-9 bg-gray-100 border-b">
          <span className="mr-64">2FA App</span>
          <Toggle onChange={() => console.log('toggle')} checked={true} />
        </div>
        <div className="border-2 py-5 px-9 flex">
          <div className="flex flex-col flex-1 space-y-4 justify-between">
            <span className="font-bold text-xl">How to enable app based authentication</span>
            <ol className="list-decimal list-inside">
              <li>
                Download and install an app (such as Google Authenticator) on your mobile device.
              </li>
              <li>Scan the QR Code</li>
              <li>Enter and verify the authentication code generated by the app.</li>
            </ol>
            <Input label="Code" className="max-w-[50ch]" placeholder="Enter Code from 2FA App" />
          </div>
          <div className="float-right justify-center items-center">
            <img
              className="max-w-[200px] max-h-[200px]"
              src="https://upload.wikimedia.org/wikipedia/commons/6/61/QR_deWP.svg"
            />
            <span className="text-center block font-bold underline">View setup key</span>
          </div>
        </div>
      </div>
    </div>
  );
};
export default UserEditTwoFactor;
