source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.3', '>= 6.1.7.3'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.6'
# Build JSON APIs with ease.
gem 'jsonapi-serializer'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

gem 'sorcery', '~> 0.16.1'
# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'
# payment provider
gem 'stripe'

# vat id validator
gem 'countries'
gem 'valvat'

# Money helper to convert cents to currency format
gem 'money'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# task scheduler
gem 'whenever', require: false

gem 'cancancan'

# config for most services
gem 'config'

# api endpoint service
gem 'faraday'
gem 'faraday_middleware'

# key discovery service
gem 'concurrent-ruby'
gem 'concurrent-ruby-edge', '~> 0.6.0'
gem 'kubeclient', '~> 4.9'

# syslog service
gem 'cef'

# telemetry
gem 'opentelemetry-api', '~> 1'
gem 'opentelemetry-exporter-otlp', '~> 0.20'
gem 'opentelemetry-instrumentation-active_job', '~> 0.1' # not included in the above
gem 'opentelemetry-instrumentation-concurrent_ruby', '~> 0.19'
gem 'opentelemetry-instrumentation-faraday', '~> 0.19'
gem 'opentelemetry-instrumentation-rails', '~> 0.19'
gem 'opentelemetry-resource_detectors', '~> 0.19'
gem 'opentelemetry-sdk', '~> 1'
gem 'prometheus-client'
gem 'rake'

# events
gem 'cloud_events'

# Mailer
gem 'mailgun-ruby', '~>1.2.5'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'pry-nav'
  gem 'pry-rails'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
  gem 'solargraph'
  gem 'stripe-ruby-mock', '~> 3.1.0.rc2', require: 'stripe_mock'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'

  gem 'listen', '~> 3.3'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener_web', '~> 2.0'
  gem 'rexml'

  # Helper for Frontend
  gem 'js-routes-rails'
  gem 'schema2type'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
  # code coverage w/ codecov.io
  gem 'simplecov', require: false
  gem 'simplecov-cobertura'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
