apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Replace "api.example.com" with your API hostname.
# Replace "ingressclassname" with your Ingress class
patches:
  - patch: |-
      - op: add
        path: /spec/rules/0/host
        value: "api.example.com"
      - op: add
        path: /spec/ingressClassName
        value: "ingressclassname"
    target:
      kind: Ingress
      name: apisrv-v2

  - path: deployment-config.yaml
    target:
      kind: Deployment
      name: apisrv-deployment-v2

configMapGenerator:
  - name: apisrv-v2-config
    files:
      - apisrv.yaml
        
resources:
  - env-secret.yaml
